service:
  name: <service_name_here>

plugins:
  - serverless-offline
  - serverless-plugin-monorepo
  - serverless-webpack
  - serverless-pseudo-parameters

provider:
  name: aws
  environment:
    APP_SECRET: ${ssm:APP_SECRET_${self:custom.stage}}
    CLIENT_ID: ${ssm:client_id_${self:custom.stage}}
    CLIENT_SECRET: ${ssm:client_secret_${self:custom.stage}}
    NODE_ENV: ${self:custom.stage}
    NOTIFICATIONS_URI: ${ssm:notifications_uri}
    DATABASE_NAME: ${ssm:dbname_${self:custom.stage}}
    DATABASE_PASSWORD: ${ssm:dbpass_${self:custom.stage}}
    DATABASE_PORT: ${ssm:dbport_${self:custom.stage}}
    DATABASE_HOST: ${ssm:dbhost_${self:custom.stage}}
    DATABASE_USER: ${ssm:dbuser_${self:custom.stage}}
  runtime: nodejs12.x
  region: ap-southeast-1
  stackName: ${self:custom.project}-${self:custom.service_name}-${self:custom.stage}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'ssm:GetParameters'
        - 'ssm:GetParameter'
      Resource: 'arn:aws:ssm:ap-southeast-1:#{AWS::AccountId}:parameter/*'
  apiGateway:
    restApiId:
      'Fn::ImportValue': ProofnAPIGateway-restApiId-${self:custom.stage}
    restApiRootResourceId:
      'Fn::ImportValue': ProofnAPIGateway-rootResourceId-${self:custom.stage}
    websocketApiId:
      'Fn::ImportValue': ProofnAPIGateway-websocketApiId-${self:custom.stage}

custom:
  project: <project_name_here>
  service_name: <service_name_here>
  stage: ${opt:stage, self:provider.stage}
  webpack:
    keepOutputDirectory: true
    packager: 'yarn'
    includeModules:
      webpackConfig: 'webpack.config.js'
      forceExclude:
        - aws-sdk
    excludeFiles: src/**/*.test.ts

package:
  individually: true

functions:
  index:
    handler: handler.index
    events:
      - http:
          method: get
          cors: true
          path: index
  create:
    handler: handler.create
    events:
      - http:
          method: post
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - kasl-key
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
          path: enter-post-path

  update:
    handler: handler.update
    events:
      - http:
          method: any
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - kasl-key
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
          path: enter-get-path/{identifier}
          request:
            parameters:
              paths:
                identifier: true
