parser: '@typescript-eslint/parser' # Specifies the ESLint parser
extends:
  - 'plugin:@typescript-eslint/recommended' # Uses the recommended rules from the @typescript-eslint/eslint-plugin
  - 'prettier/@typescript-eslint' # Uses eslint-config-prettier to disable ESLint rules from @typescript-eslint/eslint-plugin that would conflict with prettier


    # Enables eslint-plugin-prettier and eslint-config-prettier.
    # This will display prettier errors as ESLint errors. Make
    # sure this is always the last configuration in the extends
    # array.
  - 'plugin:prettier/recommended'
parserOptions:
  ecmaVersion: 2018 # Allows for the parsing of modern ECMAScript features
  sourceType: 'module' # Allows for the use of imports

rules:
  '@typescript-eslint/camelcase': off
  '@typescript-eslint/ban-types': 0
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/explicit-module-boundary-types': 0
  '@typescript-eslint/no-var-requires': 0
  '@typescript-eslint/no-use-before-define':
    ['error', { 'functions': false, 'classes': false, 'variables': true }]
  'function-call-argument-newline': ['error', 'consistent']
  'no-use-before-define': 0
